image: Visual Studio 2017
platform: x64

cache:
  - node_modules
  - '%LOCALAPPDATA%\electron\Cache'
  - '%LOCALAPPDATA%\electron-builder\cache'

install:
  - ps: Install-Product node 16

build_script:
  - yarn
  - yarn build
  - yarn prepare-release
  - yarn package appx

# test_script:
#   - yarn lint
#   - yarn test

artifacts:
  - path: 'build\clean\build\*.appx'
